language: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt
script:
    - cd ./project
    - coverage run -m unittest
after_success:
    - bash <(curl -s https://codecov.io/bash)
