language: python
python:
    - "3.8"
services:
    - docker
before_install:
    - docker pull tommywenjiezhang/python-calculator
script:
    - docker run tommywenjiezhang/python-calculator
after_success:
    - bash <(curl -s https://codecov.io/bash)
